[[Ghostscript]]
arch = "aarch64"
git-tree-sha1 = "0d9e7c35bc21411c7d9c194f790e30a95a4a5795"
os = "macos"

    [[Ghostscript.download]]
    sha256 = "1ac0c441c08946eebbabb129e334d78e06ee51943f3d8504a5977290d97c6645"
    url = "https://github.com/JuliaBinaryWrappers/Ghostscript_jll.jl/releases/download/Ghostscript-v9.55.0+4/Ghostscript.v9.55.0.aarch64-apple-darwin.tar.gz"
[[Ghostscript]]
arch = "aarch64"
git-tree-sha1 = "24094a617c1f07846d79adad6f87e9957d5d4bd3"
libc = "glibc"
os = "linux"

    [[Ghostscript.download]]
    sha256 = "5da76b7df61febb090437f252f7699ea457e89c642d2157541c30dd34a4d87c0"
    url = "https://github.com/JuliaBinaryWrappers/Ghostscript_jll.jl/releases/download/Ghostscript-v9.55.0+4/Ghostscript.v9.55.0.aarch64-linux-gnu.tar.gz"
[[Ghostscript]]
arch = "aarch64"
git-tree-sha1 = "b7f90756da8a96d0c4a587c498b09709fa0b0fd6"
libc = "musl"
os = "linux"

    [[Ghostscript.download]]
    sha256 = "a4b0a989974cef2fc9d058abaf49465ca18194eb5112173682f19ba7d26c9fc1"
    url = "https://github.com/JuliaBinaryWrappers/Ghostscript_jll.jl/releases/download/Ghostscript-v9.55.0+4/Ghostscript.v9.55.0.aarch64-linux-musl.tar.gz"
[[Ghostscript]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "503d5933b81a8dddf7174f396a936d4dca70f776"
libc = "glibc"
os = "linux"

    [[Ghostscript.download]]
    sha256 = "b55493d8b6351ddfd3b817cfcdf20ae5fead204bd54988a26b1e27ede8d5b845"
    url = "https://github.com/JuliaBinaryWrappers/Ghostscript_jll.jl/releases/download/Ghostscript-v9.55.0+4/Ghostscript.v9.55.0.armv6l-linux-gnueabihf.tar.gz"
[[Ghostscript]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "5130fb73da801d50614dd6e5ecd37c92f710b037"
libc = "musl"
os = "linux"

    [[Ghostscript.download]]
    sha256 = "edf111684eec7598e63d18e807ee3c5f305cd6f029e1b15c30d039e2c187b4f2"
    url = "https://github.com/JuliaBinaryWrappers/Ghostscript_jll.jl/releases/download/Ghostscript-v9.55.0+4/Ghostscript.v9.55.0.armv6l-linux-musleabihf.tar.gz"
[[Ghostscript]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "f36bbc4a887809aa61e1ee64fa36dcfc03e54292"
libc = "glibc"
os = "linux"

    [[Ghostscript.download]]
    sha256 = "bf5ebd24ced5a356df59808761ac742dd8717fcb07db54b234557594f703b191"
    url = "https://github.com/JuliaBinaryWrappers/Ghostscript_jll.jl/releases/download/Ghostscript-v9.55.0+4/Ghostscript.v9.55.0.armv7l-linux-gnueabihf.tar.gz"
[[Ghostscript]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "ed44f218309e85e08b9aa7acf0de42df34295aa1"
libc = "musl"
os = "linux"

    [[Ghostscript.download]]
    sha256 = "a00afc8cb22942d6abb4db1117f3cd814b57cfc259717ed3c3fee2760025dca8"
    url = "https://github.com/JuliaBinaryWrappers/Ghostscript_jll.jl/releases/download/Ghostscript-v9.55.0+4/Ghostscript.v9.55.0.armv7l-linux-musleabihf.tar.gz"
[[Ghostscript]]
arch = "i686"
git-tree-sha1 = "5164102104423cb7f1ec6746c777a185eb7b8500"
libc = "glibc"
os = "linux"

    [[Ghostscript.download]]
    sha256 = "8d73c6609155f81741207c891707465978cd7d8ce728fa66a74a87d64e8303d7"
    url = "https://github.com/JuliaBinaryWrappers/Ghostscript_jll.jl/releases/download/Ghostscript-v9.55.0+4/Ghostscript.v9.55.0.i686-linux-gnu.tar.gz"
[[Ghostscript]]
arch = "i686"
git-tree-sha1 = "522a21d85c0b48adf77d1cbcb3a0d87cb704544b"
libc = "musl"
os = "linux"

    [[Ghostscript.download]]
    sha256 = "8df64f62d09efe1bba9b9be435bbc4216434723700b7c824040c468c0bd9b3bd"
    url = "https://github.com/JuliaBinaryWrappers/Ghostscript_jll.jl/releases/download/Ghostscript-v9.55.0+4/Ghostscript.v9.55.0.i686-linux-musl.tar.gz"
[[Ghostscript]]
arch = "i686"
git-tree-sha1 = "9a8649242601e80c53aa8cecefd1e21071ad4e07"
os = "windows"

    [[Ghostscript.download]]
    sha256 = "c9ba7c47ba5f65d5f8b37075ec5fd669dc3c8b8fa371c96e02efc42d054f7b26"
    url = "https://github.com/JuliaBinaryWrappers/Ghostscript_jll.jl/releases/download/Ghostscript-v9.55.0+4/Ghostscript.v9.55.0.i686-w64-mingw32.tar.gz"
[[Ghostscript]]
arch = "powerpc64le"
git-tree-sha1 = "588ddec36324acb19094011b127055224a09183f"
libc = "glibc"
os = "linux"

    [[Ghostscript.download]]
    sha256 = "bf2d7270fa5be6cd16c832afa737371fee25d0ae8af8c85c1bf4d57380345025"
    url = "https://github.com/JuliaBinaryWrappers/Ghostscript_jll.jl/releases/download/Ghostscript-v9.55.0+4/Ghostscript.v9.55.0.powerpc64le-linux-gnu.tar.gz"
[[Ghostscript]]
arch = "x86_64"
git-tree-sha1 = "13a107f20eb662871d66c45ab758b0da25b37863"
os = "macos"

    [[Ghostscript.download]]
    sha256 = "b97a1ac2b1b254d426ce5b44ceb9c9688cab5433e9926796a401bffd842bdc65"
    url = "https://github.com/JuliaBinaryWrappers/Ghostscript_jll.jl/releases/download/Ghostscript-v9.55.0+4/Ghostscript.v9.55.0.x86_64-apple-darwin.tar.gz"
[[Ghostscript]]
arch = "x86_64"
git-tree-sha1 = "4883a6685d86b068da934537a444a6d170d71730"
libc = "glibc"
os = "linux"

    [[Ghostscript.download]]
    sha256 = "f6f227619ae092d74d89e928922428c6e7980ce103fe42f23d624da1af9e6875"
    url = "https://github.com/JuliaBinaryWrappers/Ghostscript_jll.jl/releases/download/Ghostscript-v9.55.0+4/Ghostscript.v9.55.0.x86_64-linux-gnu.tar.gz"
[[Ghostscript]]
arch = "x86_64"
git-tree-sha1 = "99147452509183cf193aec9a6171c597abdbed72"
libc = "musl"
os = "linux"

    [[Ghostscript.download]]
    sha256 = "f045a1b1358aa3ca4478ade846c50f1724a082733718a97daa7e95bb6fdd7301"
    url = "https://github.com/JuliaBinaryWrappers/Ghostscript_jll.jl/releases/download/Ghostscript-v9.55.0+4/Ghostscript.v9.55.0.x86_64-linux-musl.tar.gz"
[[Ghostscript]]
arch = "x86_64"
git-tree-sha1 = "95c1acbd5ec4d7e59284076711a4afe1d5b2e7bc"
os = "freebsd"

    [[Ghostscript.download]]
    sha256 = "6635cc624fda44b7b29b82d61b3165e8f8f62e30e0b2f73fb75f6c9b36f56d9d"
    url = "https://github.com/JuliaBinaryWrappers/Ghostscript_jll.jl/releases/download/Ghostscript-v9.55.0+4/Ghostscript.v9.55.0.x86_64-unknown-freebsd.tar.gz"
[[Ghostscript]]
arch = "x86_64"
git-tree-sha1 = "cca2b0693e0ae8df2daca37d0779bb7209f32c5f"
os = "windows"

    [[Ghostscript.download]]
    sha256 = "10a59784f8a8af509c08b8ef4c01db4ec0f71c9ddc2470b3a1711b09ea64651c"
    url = "https://github.com/JuliaBinaryWrappers/Ghostscript_jll.jl/releases/download/Ghostscript-v9.55.0+4/Ghostscript.v9.55.0.x86_64-w64-mingw32.tar.gz"
