[[Ghostscript]]
arch = "aarch64"
git-tree-sha1 = "4073b2536eefb1a5bf2b70a8a9f2356ecaeff2ed"
os = "macos"

    [[Ghostscript.download]]
    sha256 = "d039ab8cf7eba0041d20911f80f44e06e3e4230da3a8ed636ebc5d1709a66add"
    url = "https://github.com/JuliaBinaryWrappers/Ghostscript_jll.jl/releases/download/Ghostscript-v9.55.0+2/Ghostscript.v9.55.0.aarch64-apple-darwin.tar.gz"
[[Ghostscript]]
arch = "aarch64"
git-tree-sha1 = "6dfbdb6ea8792ed1c3e35b06af2e28e159556ea2"
libc = "glibc"
os = "linux"

    [[Ghostscript.download]]
    sha256 = "bc338154216ff864c21323813fd9192f553c10f2b212fe265b9fb795fa79f265"
    url = "https://github.com/JuliaBinaryWrappers/Ghostscript_jll.jl/releases/download/Ghostscript-v9.55.0+2/Ghostscript.v9.55.0.aarch64-linux-gnu.tar.gz"
[[Ghostscript]]
arch = "aarch64"
git-tree-sha1 = "cf084a5776115fed2b18bf170fd9cd1373c47162"
libc = "musl"
os = "linux"

    [[Ghostscript.download]]
    sha256 = "70befe6c0f61eb52f8dcfb844fec810c5919f76a64c0d1982da1962228e5e283"
    url = "https://github.com/JuliaBinaryWrappers/Ghostscript_jll.jl/releases/download/Ghostscript-v9.55.0+2/Ghostscript.v9.55.0.aarch64-linux-musl.tar.gz"
[[Ghostscript]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "c3b77b5645aa30f4f3c84c4d2693259c97470361"
libc = "glibc"
os = "linux"

    [[Ghostscript.download]]
    sha256 = "87ea3fa3a133531d9dec5551650cc85f29c153181f65a90dc679e5896738980d"
    url = "https://github.com/JuliaBinaryWrappers/Ghostscript_jll.jl/releases/download/Ghostscript-v9.55.0+2/Ghostscript.v9.55.0.armv6l-linux-gnueabihf.tar.gz"
[[Ghostscript]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "f5ddd440d3bbd3684b45f9af13f5f4a805762bc9"
libc = "musl"
os = "linux"

    [[Ghostscript.download]]
    sha256 = "39758c0d385e90f048e82ed31d6b06e7298e1e8d6ca9c5080fe6e577f831aa1b"
    url = "https://github.com/JuliaBinaryWrappers/Ghostscript_jll.jl/releases/download/Ghostscript-v9.55.0+2/Ghostscript.v9.55.0.armv6l-linux-musleabihf.tar.gz"
[[Ghostscript]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "9aae087c3aafcb0367acd438409d94f3f31c8b1c"
libc = "glibc"
os = "linux"

    [[Ghostscript.download]]
    sha256 = "992f8e47d81af2b082e128bf754ded651bfb282674ba47097fa1311c29a09904"
    url = "https://github.com/JuliaBinaryWrappers/Ghostscript_jll.jl/releases/download/Ghostscript-v9.55.0+2/Ghostscript.v9.55.0.armv7l-linux-gnueabihf.tar.gz"
[[Ghostscript]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "0294ad8ba5b41437efbb1e1d67827fb5ee649e7a"
libc = "musl"
os = "linux"

    [[Ghostscript.download]]
    sha256 = "181809c707c8ab0cc209aab1ebb0ed0b3a10eba5563d34b9cc49ade9ca94f758"
    url = "https://github.com/JuliaBinaryWrappers/Ghostscript_jll.jl/releases/download/Ghostscript-v9.55.0+2/Ghostscript.v9.55.0.armv7l-linux-musleabihf.tar.gz"
[[Ghostscript]]
arch = "i686"
git-tree-sha1 = "6c99a545245a42fb62383b635a5bc72599831d34"
libc = "glibc"
os = "linux"

    [[Ghostscript.download]]
    sha256 = "b6be6bcc27235d54bbef9e69ff8185bc862c691b579556f6213398daa9d74f23"
    url = "https://github.com/JuliaBinaryWrappers/Ghostscript_jll.jl/releases/download/Ghostscript-v9.55.0+2/Ghostscript.v9.55.0.i686-linux-gnu.tar.gz"
[[Ghostscript]]
arch = "i686"
git-tree-sha1 = "976904931f8badebddf38057b79a559985972f68"
libc = "musl"
os = "linux"

    [[Ghostscript.download]]
    sha256 = "27fe9ca4cb820ca8281666f60761c48b4d349bacdc9947aa3b009ce5911d17bc"
    url = "https://github.com/JuliaBinaryWrappers/Ghostscript_jll.jl/releases/download/Ghostscript-v9.55.0+2/Ghostscript.v9.55.0.i686-linux-musl.tar.gz"
[[Ghostscript]]
arch = "i686"
git-tree-sha1 = "0d49010621c171913914aff542412bc93feef337"
os = "windows"

    [[Ghostscript.download]]
    sha256 = "10b7c9312a7193cd470e775f0e7324930a944a50d61010a0839a21943766cddf"
    url = "https://github.com/JuliaBinaryWrappers/Ghostscript_jll.jl/releases/download/Ghostscript-v9.55.0+2/Ghostscript.v9.55.0.i686-w64-mingw32.tar.gz"
[[Ghostscript]]
arch = "powerpc64le"
git-tree-sha1 = "078664e79b3a8f3b7f8c6c5b1ff86b4a475ffe5d"
libc = "glibc"
os = "linux"

    [[Ghostscript.download]]
    sha256 = "923459229f6d1da2a5173404fa571efbce935086cb212122b7590de4b47136d5"
    url = "https://github.com/JuliaBinaryWrappers/Ghostscript_jll.jl/releases/download/Ghostscript-v9.55.0+2/Ghostscript.v9.55.0.powerpc64le-linux-gnu.tar.gz"
[[Ghostscript]]
arch = "x86_64"
git-tree-sha1 = "5bd77a783511be1b045bb4b6812401f6f33aa04e"
os = "macos"

    [[Ghostscript.download]]
    sha256 = "8c405437b3a227813d26dab685e9ec16aedd43de1f97d0ce4dc1c5e10358b9e7"
    url = "https://github.com/JuliaBinaryWrappers/Ghostscript_jll.jl/releases/download/Ghostscript-v9.55.0+2/Ghostscript.v9.55.0.x86_64-apple-darwin.tar.gz"
[[Ghostscript]]
arch = "x86_64"
git-tree-sha1 = "eb9b70bed98158b07f8cad331c931af0959033fd"
libc = "glibc"
os = "linux"

    [[Ghostscript.download]]
    sha256 = "6a69f4cdeacd041cb8cad1714ec15da120d55d21184344ea4707af258e16751a"
    url = "https://github.com/JuliaBinaryWrappers/Ghostscript_jll.jl/releases/download/Ghostscript-v9.55.0+2/Ghostscript.v9.55.0.x86_64-linux-gnu.tar.gz"
[[Ghostscript]]
arch = "x86_64"
git-tree-sha1 = "0ad967cfe4c09bc8026d92869ec9aebe5bbd284a"
libc = "musl"
os = "linux"

    [[Ghostscript.download]]
    sha256 = "afe8fc3e46215270013068bac6b6f01edceb9daa142dcbd331632ec0139ae2b9"
    url = "https://github.com/JuliaBinaryWrappers/Ghostscript_jll.jl/releases/download/Ghostscript-v9.55.0+2/Ghostscript.v9.55.0.x86_64-linux-musl.tar.gz"
[[Ghostscript]]
arch = "x86_64"
git-tree-sha1 = "80365925346c544304be27f9892decd6b3d81d45"
os = "freebsd"

    [[Ghostscript.download]]
    sha256 = "dbb45f4f6c2660b0e30d83f5c4ee2dad585ed394cea9369d342ffffdf26ea00f"
    url = "https://github.com/JuliaBinaryWrappers/Ghostscript_jll.jl/releases/download/Ghostscript-v9.55.0+2/Ghostscript.v9.55.0.x86_64-unknown-freebsd.tar.gz"
[[Ghostscript]]
arch = "x86_64"
git-tree-sha1 = "74a3f6c1ee1c73170966cd6aaa7b2b874816060c"
os = "windows"

    [[Ghostscript.download]]
    sha256 = "1a0725a61f62da7c1e2cb556ed83ba12993af2316833e7817f29cd93169a3dab"
    url = "https://github.com/JuliaBinaryWrappers/Ghostscript_jll.jl/releases/download/Ghostscript-v9.55.0+2/Ghostscript.v9.55.0.x86_64-w64-mingw32.tar.gz"
