[[Ghostscript]]
arch = "aarch64"
git-tree-sha1 = "ed1a49a2f4c2799f569e53d6cf9c76543c8a20ba"
libc = "glibc"
os = "linux"

    [[Ghostscript.download]]
    sha256 = "13ba314d7e298f658e99fa3b5d345c33b0dc36c994c66c1acb023e43a1d9af38"
    url = "https://github.com/JuliaBinaryWrappers/Ghostscript_jll.jl/releases/download/Ghostscript-v9.53.3+0/Ghostscript.v9.53.3.aarch64-linux-gnu.tar.gz"
[[Ghostscript]]
arch = "aarch64"
git-tree-sha1 = "d314a73dee53b0ccd5ec89d5da48cdcff26a814a"
libc = "musl"
os = "linux"

    [[Ghostscript.download]]
    sha256 = "2e29c3ed2d69552e5cf3ea3e5004fefd65d7eeeb0e565f0b7f435ffd4a23aa45"
    url = "https://github.com/JuliaBinaryWrappers/Ghostscript_jll.jl/releases/download/Ghostscript-v9.53.3+0/Ghostscript.v9.53.3.aarch64-linux-musl.tar.gz"
[[Ghostscript]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "6d6f3d7a4ae81c5bf8909fb3a6f6725193203cbb"
libc = "glibc"
os = "linux"

    [[Ghostscript.download]]
    sha256 = "2dd01068d36ae0ae9ba6d5c6da56c16beea77e2149557a7dbabea18512144477"
    url = "https://github.com/JuliaBinaryWrappers/Ghostscript_jll.jl/releases/download/Ghostscript-v9.53.3+0/Ghostscript.v9.53.3.armv7l-linux-gnueabihf.tar.gz"
[[Ghostscript]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "ef9c791366972110b64fb6472e8d8c4ca538dbd1"
libc = "musl"
os = "linux"

    [[Ghostscript.download]]
    sha256 = "132aac23f74c7ee52d190fce262df0794ffc90fad91a077713f554399abe777b"
    url = "https://github.com/JuliaBinaryWrappers/Ghostscript_jll.jl/releases/download/Ghostscript-v9.53.3+0/Ghostscript.v9.53.3.armv7l-linux-musleabihf.tar.gz"
[[Ghostscript]]
arch = "i686"
git-tree-sha1 = "883f06c9bc0f1c377bb668ce1f6111277d7cea79"
libc = "glibc"
os = "linux"

    [[Ghostscript.download]]
    sha256 = "cf96693d2682db339b7b2e00219643dfeb525452a8ed0190468c95adae80e188"
    url = "https://github.com/JuliaBinaryWrappers/Ghostscript_jll.jl/releases/download/Ghostscript-v9.53.3+0/Ghostscript.v9.53.3.i686-linux-gnu.tar.gz"
[[Ghostscript]]
arch = "i686"
git-tree-sha1 = "309add53c152a21fd4a4656d230434f267818328"
libc = "musl"
os = "linux"

    [[Ghostscript.download]]
    sha256 = "74b38f7ef545c76507f2c15523198e8e484ad5428f3a9f7b863729e50a02b7c7"
    url = "https://github.com/JuliaBinaryWrappers/Ghostscript_jll.jl/releases/download/Ghostscript-v9.53.3+0/Ghostscript.v9.53.3.i686-linux-musl.tar.gz"
[[Ghostscript]]
arch = "i686"
git-tree-sha1 = "147572a68c8ed247db670a91c57ec4f34e2aed8b"
os = "windows"

    [[Ghostscript.download]]
    sha256 = "ff58edeed0ca6004b39d2f998cd2dc7383fb0f7cbce4a4552ebcbb846822d3c7"
    url = "https://github.com/JuliaBinaryWrappers/Ghostscript_jll.jl/releases/download/Ghostscript-v9.53.3+0/Ghostscript.v9.53.3.i686-w64-mingw32.tar.gz"
[[Ghostscript]]
arch = "powerpc64le"
git-tree-sha1 = "3af683d267174cc49fa9c6733306e8f93cceee37"
libc = "glibc"
os = "linux"

    [[Ghostscript.download]]
    sha256 = "782bf94ce2e1809f4a89c4c9d70fbd559d9e457714ab1cf53f85beaa7c8bc376"
    url = "https://github.com/JuliaBinaryWrappers/Ghostscript_jll.jl/releases/download/Ghostscript-v9.53.3+0/Ghostscript.v9.53.3.powerpc64le-linux-gnu.tar.gz"
[[Ghostscript]]
arch = "x86_64"
git-tree-sha1 = "8292168b6e56d6598e8ba997417e10ffc77bdca9"
os = "macos"

    [[Ghostscript.download]]
    sha256 = "0c29c6ad51f6ad034ba6cfcf58a1ed441127db92d07c0a3c65668d4cb3c9685a"
    url = "https://github.com/JuliaBinaryWrappers/Ghostscript_jll.jl/releases/download/Ghostscript-v9.53.3+0/Ghostscript.v9.53.3.x86_64-apple-darwin.tar.gz"
[[Ghostscript]]
arch = "x86_64"
git-tree-sha1 = "c9fd2ce822167dc315c0e9c2aaa217d015662c0f"
libc = "glibc"
os = "linux"

    [[Ghostscript.download]]
    sha256 = "a4e75e450dcce41ac9a34048aeb4dc25a5b04c962987b4a49d02519739392b4c"
    url = "https://github.com/JuliaBinaryWrappers/Ghostscript_jll.jl/releases/download/Ghostscript-v9.53.3+0/Ghostscript.v9.53.3.x86_64-linux-gnu.tar.gz"
[[Ghostscript]]
arch = "x86_64"
git-tree-sha1 = "e663220f8a0489e1e8d52fe847fbc958db207d09"
libc = "musl"
os = "linux"

    [[Ghostscript.download]]
    sha256 = "04fbcd92562e4a4e4fb90ed0c594b6b779c9f7127e982e08f84da9a067caaa1b"
    url = "https://github.com/JuliaBinaryWrappers/Ghostscript_jll.jl/releases/download/Ghostscript-v9.53.3+0/Ghostscript.v9.53.3.x86_64-linux-musl.tar.gz"
[[Ghostscript]]
arch = "x86_64"
git-tree-sha1 = "d3f8769566d3c0dbdf8c9b1f7c8fd8c920bfe95a"
os = "freebsd"

    [[Ghostscript.download]]
    sha256 = "f76e225b79af06f2196af34d404ee662637730e7dc9124378b81f82c93eda718"
    url = "https://github.com/JuliaBinaryWrappers/Ghostscript_jll.jl/releases/download/Ghostscript-v9.53.3+0/Ghostscript.v9.53.3.x86_64-unknown-freebsd.tar.gz"
[[Ghostscript]]
arch = "x86_64"
git-tree-sha1 = "de6c2695ec3295b20bea6fd528f954ae93eac3f3"
os = "windows"

    [[Ghostscript.download]]
    sha256 = "80a875dd3c4f970655bb56ea5ba2f22bb9575a3ee26ba9c5123a499a294d8019"
    url = "https://github.com/JuliaBinaryWrappers/Ghostscript_jll.jl/releases/download/Ghostscript-v9.53.3+0/Ghostscript.v9.53.3.x86_64-w64-mingw32.tar.gz"
